#!/bin/bash
# Export Solidity ABI for the Stylus contract

echo "/**"
echo " * ArbShield ZK Verifier - Stylus Contract ABI"
echo " * Auto-generated Solidity interface"
echo " */"
echo ""
echo "// SPDX-License-Identifier: MIT"
echo "pragma solidity ^0.8.23;"
echo ""
echo "interface IZKVerifier {"
echo "    /// Initialize the verifier with an owner address"
echo "    function initialize(address owner) external;"
echo ""
echo "    /// Verify a Groth16 ZK proof"
echo "    /// @param proof 256 bytes containing proof points (A, B, C)"
echo "    /// @param publicInputs Array of 32-byte field elements"
echo "    /// @return bool True if proof is valid"
echo "    function verify(bytes calldata proof, bytes[] calldata publicInputs) external returns (bool);"
echo ""
echo "    /// Get total number of verified proofs"
echo "    function getVerifiedCount() external view returns (uint256);"
echo ""
echo "    /// Get the owner address"
echo "    function getOwner() external view returns (address);"
echo ""
echo "    /// Check if contract is initialized"
echo "    function isInitialized() external view returns (bool);"
echo "}"
